[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  VITE_BACKEND_URL = "https://codedevforge-codedevforge.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
 